load_model: "" # "/home/christian/MIDI-RWKV/src/outputs/8192_oldcont/17-38-11/out/rwkv-4.pth"  # if continuing: full path with .pth
wandb: "MIDI-RWKV"
tensorboard: 1
ntfy: "phantasmagoria"
proj_dir: "out"
random_seed: -1

# these will be set by the program
my_timestamp:
betas:
real_bsz:
run_name:

trainer:
    gradient_clip_val: 1.0  # reduce it to 0.7 / 0.5 / 0.3 / 0.2 for problematic samples
    max_epochs: 30 # TODO update

    num_nodes: 1
    accelerator: "gpu"
    devices:  # will be autoset
    precision: "16"  # MUST be "16" for V100
    strategy: "deepspeed_stage_2"

model:
    vocab_size: # set automatically from tokenizer
    ctx_len: 8192  # TODO modify me as you wish

    n_layer: 8  # TODO modify me as you wish
    n_embd: 512  # TODO modify me as you wish
    dim_att: 0  # 0 defaults to n_embd
    dim_ffn: 0  # 0 defautls to 3.5 * n_embd

    head_size_a: 64
    chunk_len: 16
    head_size_divisor: 8

    dropout: 0  # try 0.01/0.02/0.05/0.1
    adam_eps: 1e-18
    grad_cp: 0  # 0 = no gradient checkpointing

training:
    epoch_save: 1  # save per epochs
    save_steps: 0  # save per steps
    micro_bsz: 4  # bsz per GPU
    # 16384/8 or 8192/16 on 80GB
    # 16384/2 or 8192/4 on 24GB
    # 16384/1 or 8192/2 @ FP16 (precision: "16") on 16GB V100

    lr_schedule: # linear
    layerwise_lr: 1  # 1 = layerwise lr for faster convergence, slower it/s
    lr_init: 1e-4  # initial learning rate
    lr_final: 1e-4  # final learning rate
    warmup_steps: 20

    beta1: 0.9   # ZeRO betas
    beta2: 0.99  # ZeRO betas
    ds_bucket_mb: 200  # ZeRO bucket size MB

    weight_decay: 0.1
    weight_decay_final: -1

    dataloader_num_workers: 16

# TODO: omegaconf does not support tuples very well
data:
    # /app for docker
    src_dir: 
    prefiltered_dataset_path: ${.src_dir}/data/prefiltered
    tokenizer_path: ${.src_dir}/tokenizer/tokenizer_with_acs.json
    # these should generally not be needed
    otherwise_train_data_path: /home/christian/MMM/data/GigaMIDI/all-instruments-with-drums/train.parquet
    otherwise_val_data_path: /home/christian/MMM/data/GigaMIDI/all-instruments-with-drums/validation.parquet

    max_seq_len: ${model.ctx_len}
    tracks_selection_random_ratio_range: # (0.4, 1)
    ratio_bar_infilling: 0.75
    ratios_range_bar_infilling_duration: # (0.1, 0.4)
    acs_random_ratio_range: # (0.05, 0.9)
    tracks_idx_random_ratio_range: # (0.1, 1)
    bars_idx_random_ratio_range: # (0.1, 0.7)
    
    min_num_bars_file_valid: 8
    min_num_notes_file_valid: 100
    data_augmentation_offsets: # (6, 2, 0)  # pitch, velocity, duration
    data_chunk_num_overlap_bars: 1
