load_model: "" #  "/home/christian/MIDI-RWKV/src/outputs/2025-03-19/12-50-35/out/rwkv-2.pth"  # if continuing: full path with .pth
wandb: "MIDI-RWKV"
proj_dir: "out"
random_seed: -1

# these will be set by the program
my_timestamp:
betas:
real_bsz:
run_name:

trainer:
    gradient_clip_val: 1.0  # reduce it to 0.7 / 0.5 / 0.3 / 0.2 for problematic samples
    max_epochs: 10

    num_nodes: 1
    accelerator: "gpu"
    devices: 1  # per node
    precision: "bf16"
    strategy: "deepspeed_stage_2"

model:
    # TODO configure data input
    # TODO validation set?
    vocab_size: 16000  # TODO this should be set automatically from your tokenizer!!!
    ctx_len: 2048  # TODO tune me

    n_layer: 8  # TODO tune me
    n_embd: 512  # TODO tune me
    dim_att: 0  # 0 defaults to n_embd
    dim_ffn: 0  # 0 defautls to 3.5 * n_embd

    head_size_a: 64
    chunk_len: 16
    head_size_divisor: 8

    dropout: 0  # try 0.01/0.02/0.05/0.1
    adam_eps: 1e-18
    grad_cp: 0  # 0 = no gradient checkpointing

training:
    epoch_save: 1  # save per epochs
    save_steps: 0  # save per steps
    micro_bsz: 16  # bsz per GPU

    lr_schedule: "cosine"
    layerwise_lr: 1  # layerwise for faster convergence, slower it/s
    lr_init: 6e-4  # initial learning rate
    lr_final: 3e-5  # final learning rate
    warmup_steps: 20

    beta1: 0.9   # ZeRO betas
    beta2: 0.99  # ZeRO betas
    ds_bucket_mb: 20  # ZeRO bucket size MB

    weight_decay: 0.01  # try 0.1
    weight_decay_final: -1

    dataloader_num_workers: 8

# TODO: omegaconf does not support tuples very well
data:
    prefiltered_dataset_path: /home/christian/MIDI-RWKV/src/data/prefiltered
    otherwise_train_data_path: /home/christian/MMM/data/GigaMIDI/all-instruments-with-drums/train.parquet
    tokenizer_path: "/home/christian/MIDI-RWKV/src/tokenizer/tokenizer_with_acs.json"
    src_dir: "/home/christian/MIDI-RWKV/src"

    max_seq_len: ${model.ctx_len}
    tracks_selection_random_ratio_range: # (0.4, 1)
    ratio_bar_infilling: 0.75
    ratios_range_bar_infilling_duration: # (0.1, 0.4)
    acs_random_ratio_range: # (0.05, 0.9)
    tracks_idx_random_ratio_range: # (0.1, 1)
    bars_idx_random_ratio_range: # (0.1, 0.7)
    
    min_num_bars_file_valid: 8
    min_num_notes_file_valid: 100
    data_augmentation_offsets: # (6, 2, 0)  # pitch, velocity, duration
    data_chunk_num_overlap_bars: 1